### ISSUE TITLE
Trivial documentation bug in README.md

### ISSUE THREAD

**Issue by tomparkin** [tklauser/go-sysconf#3]
README.md has the following example:

```
func main() {
	// get clock ticks, this will return the same as C.sysconf(C._SC_CLK_TCK)
	clktck, err := sysconf.Sysconf(sysconf.SC_CLK_TCK)
	if err != nil {
		fmt.Printf("SC_CLK_TCK: %v\n", clktck)
	}
}
```

I think the if block should execute if there is no error, i.e. `if err == nil`.

Currently the example is printing the value of `clktck` if an error occurred.

**Comment by tklauser** [comment]
Thanks! Pushed 92513908778978c545cdfac50d0864e266f61622 with a fix.
