### ISSUE TITLE
`undefined: unix.ClockGetres`

### ISSUE THREAD

**Issue by terrancewong** [tklauser/go-sysconf#30]
Linux AMD64, go 1.17

``` shell
github.com/tklauser/go-sysconf/sysconf_linux.go:133:12: undefined: unix.ClockGetres
```
`golang.org/x/sys/unix/syscall_linux.go` marked ClockGetres as **Unimplemented**

```
1489 /*
1490  * Unimplemented
1491  */
1492 // AfsSyscall
1493 // Alarm
1494 // ArchPrctl
1495 // Brk
1496 // Capget
1497 // Capset
1498 // ClockGetres
```

**Comment by tklauser** [comment]
Thanks for the report. Unfortunately, I cannot reproduce this here. It seems like the version of `golang.org/x/sys/unix` you're using is outdated. The one pinned in [`go.mod`](https://github.com/tklauser/go-sysconf/blob/master/go.mod) should have `unix.ClockGetres` on Linux: https://github.com/golang/sys/blob/fe61309f888157de161a48facf03d9412635cffe/unix/zsyscall_linux.go#L530-L536
