### ISSUE TITLE
TestGetconf fails with OPEN_MAX

### ISSUE THREAD

**Issue by zhsj** [tklauser/go-sysconf#77]
```
--- FAIL: TestGetconf (0.00s)
    sysconf_test.go:87: Sysconf(OPEN_MAX/4) returned 1048576, want 1024
FAIL
```

I think it's related to https://github.com/golang/go/issues/46279

So my system OPEN_MAX is 1024, and Go just bumps it to 1024*1024. However `getconf` still reports the origin one.

**Comment by tklauser** [comment]
I think this was „fixed“ by https://github.com/tklauser/go-sysconf/pull/71. I‘ll tag a new release wirh that change included.
